services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false
      bind:
         $projectDir: '%kernel.project_dir%'
         $db: '@database_connection'
         $stringParser: '@Codefog\HasteBundle\StringParser'
         $notificationCenter: '@Terminal42\NotificationCenterBundle\NotificationCenter'
         $valueBinders: '@terminal42_leads.value_binders'
         $formatters: '@terminal42_leads.formatters'
         $translator: '@translator'
         $expressionLanguage: '@terminal42_leads.expression_language'
         $tokenDefinitionFactory: '@Terminal42\NotificationCenterBundle\Token\Definition\Factory\TokenDefinitionFactoryInterface'

   Cgoit\LeadsOptinBundle\:
      resource: ../src/*